services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Shyguy\:
    resource: '../Classes/*'

  WapplerSystems\Shyguy\EventListener\ModifyButtonBarEventListener:
    tags:
      - name: event.listener
        identifier: 'wapplersystems/shyguy/modify-button-bar'
        event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent
